/*
===============================================================================
Script: Asset Dimension Table Schema & Metadata Insertion
Description: Creates the 'Dim_Activos' dimension table storing asset profiles, 
             sector classifications, and trading parameters for Power BI reporting.
Engine: SQLite
===============================================================================
*/

CREATE TABLE Dim_Activos (
	Ticker TEXT PRIMARY KEY,
	Nombre_De_Activo TEXT,
	Origen_Geografico TEXT,
	Mercado TEXT,
	Descripcion TEXT,
	Clase_Activo TEXT,
	Subclase_Activo TEXT,
	Sector TEXT,
	Industria TEXT,
	Moneda_Origen TEXT,
	Moneda_Modelo TEXT,
	Tasa_Prestamo_Anual_Estimada REAL,
	Comision_Trade REAL,
	Horario_Mercado TEXT,
	Ventana_Modelo_Predeterminada INT,
	Volatilidad_Critica_Inicial REAL,
	Activo_Habilitado_Trading BOOLEAN DEFAULT 1
);


INSERT INTO Dim_Activos (Ticker,
	Nombre_De_Activo,
	Origen_Geografico,
	Mercado,
	Descripcion,
	Clase_Activo,
	Subclase_Activo,
	Sector,
	Industria,
	Moneda_Origen,
	Moneda_Modelo,
	Tasa_Prestamo_Anual_Estimada,
	Comision_Trade,
	Horario_Mercado ,
	Ventana_Modelo_Predeterminada,
	Volatilidad_Critica_Inicial,
	Activo_Habilitado_Trading
) VALUES
('BIMBOA.MX',
	'Grupo Bimbo S.A.B. de C.V.',
	'México',
	'BMV',
	'Grupo Bimbo, S.A.B. de C.V. produce, distribuye y comercializa productos de panificación, pan de caja, bollos, pastelería, galletas, tostadas, tortillas y botanas saladas.',
	'Acciones',
	'Acciones ordinarias Serie A.',
	'Consumer Defensive',
	'Alimentos Empacados',
	'MXN',
	'MXN',
	0.015,
	0.001,
	'Horario Bursatil' ,
	'10',
	0.015,
	1
),
('BTC-USD',
	'Bitcoin USD',
	'Descentralizado',
	'CCC',
	'Bitcoin es el primer sistema de pago digital y activo financiero descentralizado basado en una red de computadoras de igual a igual (P2P), la cual valida transacciones de forma segura mediante criptografía y tecnología blockchain sin depender de intermediarios o bancos centrales.',
	'Criptomonedas',
	'Criptomoneda nativa de suministro limitado ',
	'Tecnología Financiera',
	'Divisas Digitales',
	'BTC',
	'MXN',
	0.015,
	0.001,
	'24/7' ,
	'10',
	0.015,
	1
),
('GLD',
	'SPDR Gold Share',
	'Estados Unidos',
	'NYSE',
	'Es un fondo cotizado en bolsa (ETF) diseñado para rastrear el desempeño del precio de los lingotes de oro físico, menos los gastos operativos del fondo. Permite a los inversionistas participar en el mercado del oro sin tener que almacenar ni asegurar el metal físicamente.',
	'Materias Primas',
	'Metal Precioso',
	'Metales Preciosos',
	'Fondos De Inversión Indexados Basados En Materias Primas',
	'USD',
	'MXN',
	0.0075,
	0.001,
	'Horario Bursatil' ,
	'20',
	0.015,
	1
),
('QQQ',
	'Invesco QQQ Trust',
	'Estados Unidos',
	'NASDAQ',
	'Fondo cotizado en bolsa (ETF) que busca replicar el rendimiento de precio y rendimiento del índice Nasdaq-100, el cual incluye a las 100 empresas no financieras más grandes del mundo listadas en la bolsa NASDAQ según su capitalización de mercado.',
	'Acciones',
	'Fondo Cotizado en Bolsa',
	'Multisectorial',
	'Fondo De Inversión Indexado De Renta Variable',
	'USD',
	'MXN',
	0.015,
	0.001,
	'Horario Bursatil' ,
	'10',
	0.015,
	1
),
('SPY',
	'SPDR S&P 500 ETF Trust',
	'Estados Unidos',
	'NYSE',
	'Fondo cotizado en bolsa (ETF) que busca replicar el rendimiento de precio y rendimiento del índice S&P 500, el cual agrupa a las 500 empresas líderes de las industrias más importantes en los Estados Unidos, cubriendo aproximadamente el 80% de la capitalización de mercado disponible.',
	'Acciones',
	'Fondo Cotizado en Bolsa',
	'Multisectorial',
	'Fondo De Inversión Indexado De Renta Variable',
	'USD',
	'MXN',
	0.0075,
	0.001,
	'Horario Bursatil' ,
	'20',
	0.015,
	1
),
('TLT',
	'iShares 20+ Year Treasury Bond ETF',
	'Estados Unidos',
	'NASDAQ',
	'Fondo cotizado en bolsa (ETF) que busca replicar los resultados de inversión de un índice compuesto por bonos del Tesoro de los Estados Unidos con vencimientos remanentes superiores a los 20 años.',
	'Renta Fija',
	'Bonos Soberanos De Largo Plazo Con Grado De Inversión',
	'Gobierno',
	'Fondos De Inversión Indexados De Renta Fija',
	'USD',
	'MXN',
	0.0075,
	0.001,
	'Horario Bursatil' ,
	'20',
	0.015,
	1
),
('WALMEX.MX',
	'Walmart de Mexico S.A.B. de C.V.',
	'México',
	'BMV',
	'Wal-Mart de México, S.A.B. de C.V. es la cadena minorista más grande de la región. Opera tiendas de autoservicio, clubes de precios y farmacias bajo formatos como Bodega Aurrera, Walmart, Walmart Express y Superama.',
	'Acciones',
	'Acciones ordinarias Serie V',
	'Consumer Defensive',
	'Comercio Minorista De Alimentos',
	'MXN',
	'MXN',
	0.015,
	0.001,
	'Horario Bursatil' ,
	'10',
	0.015,
	1
)

;
